In [15]:
import pandas as pd
df1 = pd.read_csv('BTC-USD.csv')
df2=pd.read_csv('ETH-USD.csv')
df3=pd.read_csv('LEO-USD.csv')

In [16]:
df3.head()

         Date      Open      High       Low     Close  Adj Close    Volume
0  2020-12-31  1.353193  1.358826  1.351354  1.358328   1.358328   6839469
1  2021-01-01  1.358301  1.359148  1.355138  1.356405   1.356405  11099707
2  2021-01-02  1.356437  1.357634  1.354778  1.356590   1.356590  10160156
3  2021-01-03  1.356814  1.365397  1.352887  1.352928   1.352928  10087327
4  2021-01-04  1.352970  1.355393  1.347542  1.348232   1.348232  19398784

In [13]:
def function(data,name):
    # add a new column named 'Currency' with value 'BTC'
    for index, row in df1.iterrows():
        data.at[index, 'Currency'] = name

    # print the updated dataframe



function(df1,'BTC')
function(df2,'Etherum')

print(df1)
print(df2)

           Date          Open          High           Low         Close  \
0    2020-12-31  28841.574219  29244.876953  28201.992188  29001.720703
1    2021-01-01  28994.009766  29600.626953  28803.585938  29374.152344
2    2021-01-02  29376.455078  33155.117188  29091.181641  32127.267578
3    2021-01-03  32129.408203  34608.558594  32052.316406  32782.023438
4    2021-01-04  32810.949219  33440.218750  28722.755859  31971.914062
..          ...           ...           ...           ...           ...
424  2022-02-28  37706.000000  43760.457031  37518.214844  43193.234375
425  2022-03-01  43194.503906  44793.601562  42952.585938  44354.636719
426  2022-03-02  44357.617188  45077.578125  43432.851562  43924.117188
427  2022-03-03  43925.195312  44021.578125  41914.750000  42451.789062
428  2022-03-06  39397.218750  39625.664062  38219.726562  38748.148438

        Adj Close       Volume Currency
0    29001.720703  46754964848      BTC
1    29374.152344  40730301359      BTC
2    32127.267578  67865420765      BTC
3    32782.023438  78665235202      BTC
4    31971.914062  81163475344      BTC
..            ...          ...      ...
424  43193.234375  35690014104      BTC
425  44354.636719  32479047645      BTC
426  43924.117188  29183112630      BTC
427  42451.789062  24967782593      BTC
428  38748.148438  18043248640      BTC

[429 rows x 8 columns]
           Date         Open         High          Low        Close  \
0    2020-12-31   751.626648   754.299438   726.511902   737.803406
1    2021-01-01   737.708374   749.201843   719.792236   730.367554
2    2021-01-02   730.402649   786.798462   718.109497   774.534973
3    2021-01-03   774.511841  1006.565002   771.561646   975.507690
4    2021-01-04   977.058838  1153.189209   912.305359  1040.233032
..          ...          ...          ...          ...          ...
424  2022-02-28  2621.172119  2929.180420  2586.388184  2919.201172
425  2022-03-01  2919.775879  3029.651611  2868.938965  2972.485107
426  2022-03-02  2972.471924  3026.868164  2919.943115  2950.118408
427  2022-03-03  2950.156738  2964.673340  2797.319336  2834.468994
428  2022-03-06  2664.689941  2672.086914  2596.819092  2611.436768

       Adj Close       Volume Currency
0     737.803406  13926846861  Etherum
1     730.367554  13652004358  Etherum
2     774.534973  19740771179  Etherum
3     975.507690  45200463368  Etherum
4    1040.233032  56945985763  Etherum
..           ...          ...      ...
424  2919.201172  19266124733  Etherum
425  2972.485107  18757425786  Etherum
426  2950.118408  16636517503  Etherum
427  2834.468994  13091199728  Etherum
428  2611.436768   7832407552  Etherum

[429 rows x 8 columns]